version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=*dm#8(25(#7guoi*r)jnm&t!=&@a7@f9a)&jey^db%6#mn#p2=
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_xyVYPCzZbGjYIu0WdovYu6f800C6oJMDqo
      - STRIPE_TEST_SECRET_KEY=sk_test_LyRAWi4BvrA8rAiPNLId3hap00a6CUEWdU
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:
